"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Section = "Visão geral" | "Alunos" | "Frequência" | "Admissões" | "Ocorrências" | "Funcionários" | "Materiais e livros" | "Documentos" | "Backup";
type Pickup = { name: string; relation: string; document: string; photo?: string };
type Student = { id: number; name: string; classroom: string; guardian: string; phone: string; emergencyName: string; emergencyPhone: string; medical: string; allergies: string; occurrences: string[]; pickups: Pickup[]; documentsComplete: boolean };
type Employee = { id: number; name: string; role: string; cpf: string; rg: string; pis: string; address: string; documents: string[]; qualifications: string; training: number; attendance: number };

const sections: { label: Section; icon: string }[] = [
  { label: "Visão geral", icon: "⌂" }, { label: "Alunos", icon: "♙" }, { label: "Frequência", icon: "✓" },
  { label: "Admissões", icon: "+" }, { label: "Ocorrências", icon: "!" }, { label: "Funcionários", icon: "♧" },
  { label: "Materiais e livros", icon: "▤" }, { label: "Documentos", icon: "▱" }, { label: "Backup", icon: "↻" },
];

const initialStudents: Student[] = [
  { id: 1, name: "Ana Paula Souza", classroom: "3º ano A", guardian: "Márcia Souza", phone: "(11) 98745-2210", emergencyName: "Carlos Souza (pai)", emergencyPhone: "(11) 97631-4402", medical: "Acompanhamento com alergista", allergies: "Dipirona", occurrences: ["03/08 — Queda leve durante o recreio. Responsável avisado."], documentsComplete: true, pickups: [{ name: "Márcia Souza", relation: "Mãe", document: "RG 44.***.***-2" }, { name: "Carlos Souza", relation: "Pai", document: "CNH 08***" }] },
  { id: 2, name: "Lucas Almeida", classroom: "Infantil II", guardian: "Rafael Almeida", phone: "(11) 99820-4431", emergencyName: "Paula Almeida (tia)", emergencyPhone: "(11) 96755-1230", medical: "Sem histórico relevante", allergies: "Nenhuma informada", occurrences: [], documentsComplete: false, pickups: [{ name: "Rafael Almeida", relation: "Pai", document: "RG 39.***.***-8" }] },
  { id: 3, name: "João Pedro Silva", classroom: "2º ano B", guardian: "Juliana Silva", phone: "(11) 97731-8860", emergencyName: "Roberto Silva (avô)", emergencyPhone: "(11) 94420-5512", medical: "Uso contínuo de bombinha", allergies: "Poeira", occurrences: ["01/08 — Falta sem justificativa; família contatada."], documentsComplete: false, pickups: [{ name: "Juliana Silva", relation: "Mãe", document: "RG 48.***.***-9" }] },
];

const initialEmployees: Employee[] = [
  { id: 1, name: "Camila Ferreira", role: "Professora", cpf: "***.481.***-02", rg: "43.***.***-7", pis: "***.55231.**-4", address: "Poá/SP", documents: ["RG", "CPF", "Comprovante de endereço", "Currículo", "Certificações", "PIS"], qualifications: "Pedagogia; pós em Alfabetização", training: 92, attendance: 98 },
  { id: 2, name: "Bruno Martins", role: "Auxiliar de classe", cpf: "***.702.***-19", rg: "51.***.***-3", pis: "***.90241.**-1", address: "Suzano/SP", documents: ["RG", "CPF", "Comprovante de endereço", "Currículo"], qualifications: "Curso de primeiros socorros", training: 64, attendance: 94 },
];

export default function Home() {
  const [active, setActive] = useState<Section>("Visão geral");
  const [students, setStudents] = useState(initialStudents);
  const [employees, setEmployees] = useState(initialEmployees);
  const [selected, setSelected] = useState<Student | null>(null);
  const [studentModal, setStudentModal] = useState(false);
  const [employeeModal, setEmployeeModal] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [toast, setToast] = useState("");

  useEffect(() => {
    try {
      const savedStudents = localStorage.getItem("edugestao-students-v2");
      const savedEmployees = localStorage.getItem("edugestao-employees-v2");
      if (savedStudents) setStudents(JSON.parse(savedStudents));
      if (savedEmployees) setEmployees(JSON.parse(savedEmployees));
    } catch {}
  }, []);

  function notify(message: string) { setToast(message); setTimeout(() => setToast(""), 2600); }
  function saveStudents(next: Student[]) { setStudents(next); localStorage.setItem("edugestao-students-v2", JSON.stringify(next)); }
  function saveEmployees(next: Employee[]) { setEmployees(next); localStorage.setItem("edugestao-employees-v2", JSON.stringify(next)); }
  function go(section: Section) { setActive(section); setMobileOpen(false); }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? "open" : ""}`}>
      <div className="brand"><span className="brand-mark">✦</span><span>EduGestão</span></div>
      <nav>{sections.map(item => <button key={item.label} className={active === item.label ? "active" : ""} onClick={() => go(item.label)}><span className="nav-icon">{item.icon}</span>{item.label}{item.label === "Documentos" && <b className="badge">2</b>}</button>)}</nav>
      <div className="sidebar-bottom"><button><span className="nav-icon">⚙</span>Configurações</button></div>
    </aside>
    {mobileOpen && <button className="scrim" aria-label="Fechar menu" onClick={() => setMobileOpen(false)} />}
    <main>
      <header className="topbar"><button className="menu" onClick={() => setMobileOpen(true)}>☰</button><div className="top-actions"><button className="round">♧<span>3</span></button><div className="avatar">MS</div><div className="profile"><strong>Mariana Silva</strong><small>Diretora</small></div></div></header>
      <div className="content">
        {active === "Visão geral" && <Dashboard go={go} students={students} employees={employees} />}
        {active === "Alunos" && <Students students={students} onOpen={setSelected} onAdd={() => setStudentModal(true)} />}
        {active === "Frequência" && <Attendance students={students} employees={employees} notify={notify} />}
        {active === "Admissões" && <Admissions students={students} onOpen={setSelected} onAdd={() => setStudentModal(true)} />}
        {active === "Ocorrências" && <Occurrences students={students} save={saveStudents} notify={notify} />}
        {active === "Funcionários" && <Employees employees={employees} onAdd={() => setEmployeeModal(true)} />}
        {active === "Materiais e livros" && <Materials notify={notify} />}
        {active === "Documentos" && <Documents students={students} onOpen={setSelected} notify={notify} />}
        {active === "Backup" && <Backup students={students} employees={employees} restore={(s,e) => {saveStudents(s);saveEmployees(e)}} notify={notify} />}
      </div>
    </main>
    {selected && <StudentFile student={selected} onClose={() => setSelected(null)} notify={notify} />}
    {studentModal && <StudentForm onClose={() => setStudentModal(false)} onSave={student => { saveStudents([student, ...students]); setStudentModal(false); notify("Aluno cadastrado com sucesso!"); }} />}
    {employeeModal && <EmployeeForm onClose={() => setEmployeeModal(false)} onSave={employee => { saveEmployees([employee, ...employees]); setEmployeeModal(false); notify("Funcionário cadastrado com sucesso!"); }} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </div>;
}

function Title({title, subtitle, children}:{title:string;subtitle:string;children?:React.ReactNode}) { return <section className="page-heading compact"><div><h1>{title}</h1><p>{subtitle}</p></div>{children}</section> }
function Kpi({value,label,tone}:{value:string;label:string;tone:string}) { return <article className="stat-card"><span className={`stat-icon ${tone}`}>◇</span><div><strong>{value}</strong><p>{label}</p></div></article> }

function Dashboard({go,students,employees}:{go:(s:Section)=>void;students:Student[];employees:Employee[]}) { return <>
  <section className="page-heading"><div><p className="eyebrow">PAINEL ADMINISTRATIVO</p><h1>Boa tarde, Mariana 👋</h1><p>Acompanhe alunos, equipe e rotina escolar em um só lugar.</p></div></section>
  <section className="stats"><Kpi value={String(students.length)} label="alunos cadastrados" tone="purple"/><Kpi value="94%" label="presença hoje" tone="teal"/><Kpi value={String(employees.length)} label="funcionários" tone="amber"/><Kpi value={String(students.filter(s=>!s.documentsComplete).length)} label="documentações pendentes" tone="coral"/></section>
  <section className="feature-grid">
    {[['Frequência','Presenças e faltas de alunos e funcionários','✓'],['Ocorrências','Registros dos alunos e comunicação à família','!'],['Funcionários','Documentos, treinamentos e qualificações','♧'],['Materiais e livros','Matérias escolares, estoque e compras','▤'],['Backup','Exportação e restauração dos dados','↻']].map(x=><button className="feature-card panel" key={x[0]} onClick={()=>go(x[0] as Section)}><span>{x[2]}</span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><b>→</b></button>)}
  </section>
  <article className="panel wide-panel"><div className="panel-head"><h2>Atenções de hoje</h2></div><div className="alert-list"><div><span className="coral-dot">!</span><strong>2 alunos com documentos incompletos</strong><button onClick={()=>go("Documentos")}>Ver pendências</button></div><div><span className="amber-dot">!</span><strong>1 treinamento de funcionário próximo do prazo</strong><button onClick={()=>go("Funcionários")}>Acompanhar</button></div></div></article>
  </> }

function Students({students,onOpen,onAdd}:{students:Student[];onOpen:(s:Student)=>void;onAdd:()=>void}) { const [search,setSearch]=useState(""); const shown=useMemo(()=>students.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())),[students,search]); return <><Title title="Alunos" subtitle="Cadastro completo, saúde, responsáveis e documentos."><button className="primary" onClick={onAdd}>＋ Cadastrar aluno</button></Title><div className="toolbar panel"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar aluno..."/></label></div><div className="panel table-wrap"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Responsável</th><th>Emergência</th><th>Documentos</th><th></th></tr></thead><tbody>{shown.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.classroom}</td><td>{s.guardian}<small>{s.phone}</small></td><td>{s.emergencyName}<small>{s.emergencyPhone}</small></td><td><em className={s.documentsComplete?'teal':'coral'}>{s.documentsComplete?'Completo':'Pendente'}</em></td><td><button className="table-action" onClick={()=>onOpen(s)}>Abrir ficha</button></td></tr>)}</tbody></table></div></> }

function Attendance({students,employees,notify}:{students:Student[];employees:Employee[];notify:(s:string)=>void}) { const [tab,setTab]=useState<'Alunos'|'Funcionários'>('Alunos'); const people=tab==='Alunos'?students.map(s=>({id:s.id,name:s.name,detail:s.classroom})):employees.map(e=>({id:e.id,name:e.name,detail:e.role})); const [marks,setMarks]=useState<Record<string,string>>({}); return <><Title title="Controle de frequência" subtitle="Registre faltas, presenças e justificativas."><button className="primary" onClick={()=>notify('Frequência salva com sucesso!')}>✓ Salvar frequência</button></Title><div className="segmented"><button className={tab==='Alunos'?'active':''} onClick={()=>setTab('Alunos')}>Alunos</button><button className={tab==='Funcionários'?'active':''} onClick={()=>setTab('Funcionários')}>Funcionários</button></div><article className="panel attendance-list">{people.map(p=><div key={p.id}><span className="mini-avatar purple">{p.name[0]}</span><div><strong>{p.name}</strong><small>{p.detail}</small></div>{['Presente','Falta','Justificada'].map(v=><button key={v} className={marks[`${tab}-${p.id}`]===v?`selected ${v.toLowerCase()}`:''} onClick={()=>setMarks({...marks,[`${tab}-${p.id}`]:v})}>{v}</button>)}</div>)}</article></> }

function Admissions({students,onOpen,onAdd}:{students:Student[];onOpen:(s:Student)=>void;onAdd:()=>void}) { return <><Title title="Admissões" subtitle="Acompanhe os dados e documentos de cada novo aluno."><button className="primary" onClick={onAdd}>＋ Nova admissão</button></Title><div className="admission-grid">{[['Dados cadastrais','18'],['Documentos enviados','14'],['Análise da secretaria','9'],['Matrícula concluída','6']].map((x,i)=><article className="panel stage" key={x[0]}><div className="stage-num">{i+1}</div><h3>{x[0]}</h3><strong>{x[1]} <small>processos</small></strong><div className="progress"><i style={{width:`${90-i*17}%`}}/></div></article>)}</div><article className="panel wide-panel"><div className="panel-head"><h2>Fichas em análise</h2></div><div className="simple-list">{students.slice(0,3).map(s=><div key={s.id}><span className="mini-avatar purple">{s.name[0]}</span><strong>{s.name}</strong><button onClick={()=>onOpen(s)}>Abrir dados e documentos</button></div>)}</div></article></> }

function Occurrences({students,save,notify}:{students:Student[];save:(s:Student[])=>void;notify:(s:string)=>void}) { const [studentId,setStudentId]=useState(String(students[0]?.id||'')); const [text,setText]=useState(''); function add(){if(!text.trim())return;save(students.map(s=>s.id===Number(studentId)?{...s,occurrences:[`${new Date().toLocaleDateString('pt-BR')} — ${text}`,...s.occurrences]}:s));setText('');notify('Ocorrência registrada e vinculada ao aluno.')} return <><Title title="Ocorrências dos alunos" subtitle="Registre fatos, providências e comunicação aos responsáveis."/><article className="panel occurrence-form"><select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Descreva a ocorrência, providências tomadas e quem foi avisado..."/><button className="primary" onClick={add}>Registrar ocorrência</button></article><div className="occurrence-grid">{students.flatMap(s=>s.occurrences.map((o,i)=><article className="panel occurrence" key={`${s.id}-${i}`}><strong>{s.name}</strong><p>{o}</p><small>Responsável principal: {s.guardian} • {s.phone}</small></article>))}</div></> }

function Employees({employees,onAdd}:{employees:Employee[];onAdd:()=>void}) { return <><Title title="Funcionários" subtitle="Cadastro, documentação, qualificações e treinamentos."><button className="primary" onClick={onAdd}>＋ Cadastrar funcionário</button></Title><section className="stats small"><Kpi value={String(employees.length)} label="funcionários ativos" tone="purple"/><Kpi value="96%" label="presença no mês" tone="teal"/><Kpi value="1" label="documentação pendente" tone="coral"/></section><div className="employee-grid">{employees.map(e=><article className="panel employee" key={e.id}><div className="employee-head"><span className="mini-avatar purple">{e.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><h3>{e.name}</h3><p>{e.role}</p></div><em className={e.documents.length>=6?'teal':'coral'}>{e.documents.length>=6?'Docs. completos':'Docs. pendentes'}</em></div><dl><div><dt>RG</dt><dd>{e.rg}</dd></div><div><dt>CPF</dt><dd>{e.cpf}</dd></div><div><dt>PIS</dt><dd>{e.pis}</dd></div><div><dt>Endereço</dt><dd>{e.address}</dd></div></dl><p><b>Qualificações:</b> {e.qualifications}</p><label>Progresso dos treinamentos <strong>{e.training}%</strong><span className="progress"><i style={{width:`${e.training}%`}}/></span></label><small>Presença mensal: {e.attendance}%</small><button className="table-action">Abrir documentação</button></article>)}</div></> }

function Materials({notify}:{notify:(s:string)=>void}) { const subjects=[['Português','3º ano','Livro do aluno + atividades'],['Matemática','3º ano','Coleção Aprender'],['Ciências','2º ano','Descobertas'],['História e Geografia','4º ano','Caminhos do Saber']]; return <><Title title="Matérias e livros" subtitle="Organize matérias escolares, estoque e compras de livros."><button className="primary" onClick={()=>notify('Nova compra iniciada')}>＋ Registrar compra</button></Title><section className="stats small"><Kpi value="12" label="matérias cadastradas" tone="purple"/><Kpi value="386" label="livros em estoque" tone="teal"/><Kpi value="24" label="livros para comprar" tone="coral"/></section><article className="panel wide-panel"><div className="panel-head"><h2>Livros por matéria</h2><button onClick={()=>notify('Lista de compras exportada')}>Exportar lista ↗</button></div><div className="book-list">{subjects.map((x,i)=><div key={x[0]}><span className={`book-icon ${i%2?'teal':'purple'}`}>▤</span><div><strong>{x[0]}</strong><small>{x[1]} • {x[2]}</small></div><span>{i===1?'18 pendentes':'Estoque disponível'}</span><button onClick={()=>notify('Detalhes da matéria abertos')}>Gerenciar</button></div>)}</div></article></> }

function Documents({students,onOpen,notify}:{students:Student[];onOpen:(s:Student)=>void;notify:(s:string)=>void}) { return <><Title title="Documentos dos alunos" subtitle="Abra a pasta individual para anexar documentos e fotos."/><div className="document-grid">{students.map(s=><article className={`panel document-card ${s.documentsComplete?'complete':'missing'}`} key={s.id}><div className="folder">▱</div><h3>{s.name}</h3><p>{s.classroom} • Responsável: {s.guardian}</p><strong>{s.documentsComplete?'Documentação completa':'Faltam documentos'}</strong><div><button onClick={()=>onOpen(s)}>Abrir pasta</button><label className="table-action">Anexar<input type="file" hidden onChange={()=>notify('Documento anexado à pasta do aluno')}/></label></div></article>)}</div></> }

function Backup({students,employees,restore,notify}:{students:Student[];employees:Employee[];restore:(s:Student[],e:Employee[])=>void;notify:(s:string)=>void}) { function download(){const data=JSON.stringify({version:1,createdAt:new Date().toISOString(),students,employees},null,2);const url=URL.createObjectURL(new Blob([data],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`backup-edugestao-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);notify('Backup criado e baixado com sucesso!')} function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));restore(data.students||[],data.employees||[]);notify('Backup restaurado com sucesso!')}catch{notify('Arquivo de backup inválido.')}};reader.readAsText(file)} return <><Title title="Backup dos dados" subtitle="Proteja e restaure as informações do sistema."/><section className="backup-grid"><article className="panel backup-card"><span>↓</span><h2>Criar backup</h2><p>Gere uma cópia de alunos, responsáveis, ocorrências, funcionários e treinamentos.</p><button className="primary" onClick={download}>Baixar backup agora</button></article><article className="panel backup-card"><span>↑</span><h2>Restaurar backup</h2><p>Selecione um arquivo de backup anterior para recuperar os registros.</p><label className="secondary upload-button">Selecionar arquivo<input type="file" accept="application/json" hidden onChange={upload}/></label></article></section><article className="panel backup-status"><strong>Último backup</strong><span>Aguardando primeiro backup manual</span><em className="amber">Recomendado: fazer diariamente</em></article></> }

function StudentFile({student,onClose,notify}:{student:Student;onClose:()=>void;notify:(s:string)=>void}) { return <div className="modal-backdrop"><section className="modal student-file"><div className="modal-head"><div><h2>{student.name}</h2><span>Ficha completa do aluno</span></div><button onClick={onClose}>×</button></div><div className="file-body"><div className="file-section"><h3>Contatos e emergência</h3><p><b>Responsável:</b> {student.guardian} — {student.phone}</p><p><b>Avisar em emergência:</b> {student.emergencyName} — {student.emergencyPhone}</p></div><div className="file-section"><h3>Histórico médico</h3><p>{student.medical}</p><p><b>Alergias/restrições:</b> {student.allergies}</p></div><div className="file-section"><h3>Autorizados para retirada ({student.pickups.length}/4)</h3>{student.pickups.map((p,i)=><div className="pickup" key={i}><span className="mini-avatar teal">{p.name[0]}</span><div><strong>{p.name}</strong><small>{p.relation} • {p.document}</small></div><label className="table-action">Anexar foto do documento<input type="file" accept="image/*" hidden onChange={()=>notify('Foto do documento anexada')}/></label></div>)}{student.pickups.length<4&&<button className="secondary" onClick={()=>notify('Novo responsável autorizado adicionado')}>＋ Adicionar autorizado</button>}</div><div className="file-section"><h3>Ocorrências</h3>{student.occurrences.length?student.occurrences.map(o=><p key={o}>• {o}</p>):<p>Nenhuma ocorrência registrada.</p>}</div><div className="file-section"><h3>Documentação</h3><p className={student.documentsComplete?'teal':'coral'}><b>{student.documentsComplete?'Completa':'Pendente'}</b></p><label className="primary upload-button">Anexar documento ou foto<input type="file" hidden onChange={()=>notify('Arquivo anexado à pasta do aluno')}/></label></div></div></section></div> }

function StudentForm({onClose,onSave}:{onClose:()=>void;onSave:(s:Student)=>void}) { function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:Date.now(),name:String(f.get('name')),classroom:String(f.get('classroom')),guardian:String(f.get('guardian')),phone:String(f.get('phone')),emergencyName:String(f.get('emergencyName')),emergencyPhone:String(f.get('emergencyPhone')),medical:String(f.get('medical')),allergies:String(f.get('allergies')),occurrences:[],pickups:[{name:String(f.get('guardian')),relation:'Responsável principal',document:String(f.get('guardianDocument'))}],documentsComplete:false})} return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><div><h2>Cadastrar aluno</h2><span>Dados pessoais, saúde e emergência</span></div><button onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid"><label>Nome completo<input name="name" required/></label><label>Turma<input name="classroom" required/></label><label>Responsável principal<input name="guardian" required/></label><label>Telefone<input name="phone" required/></label><label>Documento do responsável<input name="guardianDocument" required/></label><label>Contato para emergência<input name="emergencyName" required/></label><label>Telefone de emergência<input name="emergencyPhone" required/></label><label>Histórico médico<input name="medical"/></label><label className="full">Alergias e restrições<input name="allergies"/></label><label className="full file-input">Documentos e fotos do aluno<input type="file" multiple/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Salvar aluno</button></div></form></section></div> }

function EmployeeForm({onClose,onSave}:{onClose:()=>void;onSave:(e:Employee)=>void}) { function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:Date.now(),name:String(f.get('name')),role:String(f.get('role')),cpf:String(f.get('cpf')),rg:String(f.get('rg')),pis:String(f.get('pis')),address:String(f.get('address')),qualifications:String(f.get('qualifications')),documents:[],training:0,attendance:100})} return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><div><h2>Cadastrar funcionário</h2><span>Dados, documentos e qualificações</span></div><button onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid"><label>Nome completo<input name="name" required/></label><label>Cargo<input name="role" required/></label><label>RG<input name="rg" required/></label><label>CPF<input name="cpf" required/></label><label>PIS<input name="pis" required/></label><label>Comprovante/endereço<input name="address" required/></label><label className="full">Demais qualificações<input name="qualifications"/></label><label className="full file-input">Currículo, certificações e documentos<input type="file" multiple/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Salvar funcionário</button></div></form></section></div> }
