"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Student = { id:number; name:string; email:string; phone:string; address:string; enrollmentDate:string; classroom:string; monthlyFee:number; dueDay:number };
type Transaction = { id:number; studentId:number|null; studentName:string|null; type:"receita"|"despesa"; description:string; amount:number; dueDate:string|null; paidAt:string|null; status:"pago"|"pendente"|"atrasado"; createdAt:string };
type FileRow = { id:number; studentId:number; name:string; contentType:string; createdAt:string };
type Data = { students:Student[]; transactions:Transaction[]; files:FileRow[] };
type Page = "Dashboard"|"Alunos"|"Financeiro"|"Documentos"|"Relatórios";

const fallbackData:Data = {
  students:[
    {id:1,name:"Aluno Exemplo 01",email:"responsavel01@exemplo.com",phone:"11000000001",address:"Endereço cadastrado",enrollmentDate:"2026-02-03",classroom:"3º ano A",monthlyFee:850,dueDay:5},
    {id:2,name:"Aluno Exemplo 02",email:"responsavel02@exemplo.com",phone:"11000000002",address:"Endereço cadastrado",enrollmentDate:"2026-02-05",classroom:"Infantil II",monthlyFee:780,dueDay:10},
    {id:3,name:"Aluno Exemplo 03",email:"responsavel03@exemplo.com",phone:"11000000003",address:"Endereço cadastrado",enrollmentDate:"2026-01-29",classroom:"2º ano B",monthlyFee:820,dueDay:8},
  ],
  transactions:[
    {id:1,studentId:1,studentName:"Aluno Exemplo 01",type:"receita",description:"Mensalidade agosto",amount:850,dueDate:"2026-08-05",paidAt:null,status:"atrasado",createdAt:"2026-08-05"},
    {id:2,studentId:2,studentName:"Aluno Exemplo 02",type:"receita",description:"Mensalidade agosto",amount:780,dueDate:"2026-08-10",paidAt:null,status:"pendente",createdAt:"2026-08-01"},
    {id:3,studentId:3,studentName:"Aluno Exemplo 03",type:"receita",description:"Mensalidade agosto",amount:820,dueDate:"2026-08-08",paidAt:"2026-08-04",status:"pago",createdAt:"2026-08-01"},
    {id:4,studentId:null,studentName:null,type:"despesa",description:"Compra de materiais pedagógicos",amount:1260,dueDate:null,paidAt:"2026-08-03",status:"pago",createdAt:"2026-08-03"},
  ], files:[]
};

const money = (value:number) => new Intl.NumberFormat("pt-BR", {style:"currency",currency:"BRL"}).format(value);
const nav:{page:Page;icon:string;hint:string}[] = [
  {page:"Dashboard",icon:"⌂",hint:"Resumo da escola"},{page:"Alunos",icon:"♙",hint:"Cadastros e contatos"},
  {page:"Financeiro",icon:"R$",hint:"Cobranças e transações"},{page:"Documentos",icon:"▱",hint:"Arquivos dos alunos"},{page:"Relatórios",icon:"▤",hint:"Receitas e despesas"},
];

const CACHE_KEY = "edugestao-offline-data";
function readCachedData():Data|null{try{const value=localStorage.getItem(CACHE_KEY);return value?JSON.parse(value):null}catch{return null}}
function cacheData(value:Data){try{localStorage.setItem(CACHE_KEY,JSON.stringify(value))}catch{/* armazenamento indisponível */}}

export default function Home(){
  const [page,setPage]=useState<Page>("Dashboard"); const [data,setData]=useState<Data>({students:[],transactions:[],files:[]});
  const [loading,setLoading]=useState(true); const [menu,setMenu]=useState(false); const [studentModal,setStudentModal]=useState(false); const [selectedStudent,setSelectedStudent]=useState<Student|null>(null); const [toast,setToast]=useState("");
  const [online,setOnline]=useState(true); const [lastSync,setLastSync]=useState("");
  async function load(){setLoading(true);try{const res=await fetch("/api/crm");if(!res.ok)throw new Error();const next=await res.json();setData(next);cacheData(next);setLastSync(new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}))}catch{setData(readCachedData()||fallbackData)}finally{setLoading(false)}}
  // A carga inicial sincroniza a interface com o banco persistente.
  useEffect(()=>{
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setOnline(navigator.onLine);
    const connected=()=>{setOnline(true);load();notify("Conexão restabelecida. Dados sincronizados.")};
    const disconnected=()=>{setOnline(false);notify("Modo offline ativado. Você pode continuar consultando os dados salvos.")};
    window.addEventListener("online",connected);window.addEventListener("offline",disconnected);
    if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});
    load();return()=>{window.removeEventListener("online",connected);window.removeEventListener("offline",disconnected)};
  },[]);
  function notify(msg:string){setToast(msg);setTimeout(()=>setToast(""),2800)}
  function go(next:Page){setPage(next);setMenu(false)}
  return <div className="crm-shell">
    <aside className={menu?"open":""}>
      <div className="logo"><span>e</span><div><strong>EduGestão</strong><small>CRM Escolar</small></div></div>
      <nav>{nav.map(item=><button key={item.page} className={page===item.page?"active":""} onClick={()=>go(item.page)}><b>{item.icon}</b><span>{item.page}<small>{item.hint}</small></span>{item.page==="Financeiro"&&data.transactions.some(t=>t.status==="atrasado")&&<i>!</i>}</button>)}</nav>
      <div className="school-card"><small>UNIDADE ATIVA</small><strong>Colégio Primavera</strong><span>São Paulo • SP</span></div>
      <button className="logout">↪ Sair com segurança</button>
    </aside>
    {menu&&<button className="scrim" onClick={()=>setMenu(false)} aria-label="Fechar menu"/>}
    <main>
      <header><button className="hamb" onClick={()=>setMenu(true)}>☰</button><label className="global-search">⌕ <input placeholder="Buscar aluno, cobrança ou documento..."/></label><div className={online?"connection online":"connection offline"}><i/>{online?`Online${lastSync?` • ${lastSync}`:""}`:"Modo offline"}</div><button className="help">?</button><button className="bell">♧<i>{data.transactions.filter(t=>t.status==="atrasado").length}</i></button><div className="user"><span>GE</span><div><strong>Gestora Escolar</strong><small>Direção</small></div></div></header>
      <div className="workspace">
        {loading?<div className="loading">Carregando dados da escola...</div>:<>
          {page==="Dashboard"&&<Dashboard data={data} go={go}/>} {page==="Alunos"&&<Students data={data} onAdd={()=>setStudentModal(true)} onOpen={setSelectedStudent}/>} {page==="Financeiro"&&<Finance data={data} reload={load} notify={notify}/>} {page==="Documentos"&&<Documents data={data} reload={load} notify={notify}/>} {page==="Relatórios"&&<Reports data={data}/>} 
        </>}
      </div>
    </main>
    {studentModal&&<StudentForm close={()=>setStudentModal(false)} done={()=>{setStudentModal(false);load();notify("Aluno cadastrado com sucesso!")}}/>}
    {selectedStudent&&<StudentProfile student={selectedStudent} data={data} close={()=>setSelectedStudent(null)}/>} 
    {toast&&<div className="toast">✓ {toast}</div>}
  </div>
}

function Heading({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="heading"><div><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}
function whatsapp(student:Student,transaction:Transaction){const phone=student.phone.replace(/\D/g,"");const text=`Olá, responsável por ${student.name}. Identificamos a mensalidade no valor de ${money(transaction.amount)}, com vencimento em ${new Date(transaction.dueDate+"T12:00:00").toLocaleDateString("pt-BR")}, ainda em aberto. Podemos ajudar com alguma informação?`;window.open(`https://wa.me/55${phone}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer")}

function Dashboard({data,go}:{data:Data;go:(p:Page)=>void}){
  const revenue=data.transactions.filter(t=>t.type==="receita"&&t.status==="pago").reduce((a,t)=>a+t.amount,0);const expense=data.transactions.filter(t=>t.type==="despesa").reduce((a,t)=>a+t.amount,0);const overdue=data.transactions.filter(t=>t.status==="atrasado");
  return <><Heading title="Visão geral" subtitle="Tudo o que precisa da sua atenção hoje, em um só lugar."><button className="primary" onClick={()=>go("Alunos")}>＋ Cadastrar aluno</button></Heading>
    {overdue.length>0&&<section className="overdue-alert"><span>!</span><div><strong>{overdue.length} mensalidade em atraso precisa de atenção</strong><p>Entre em contato com o responsável ou consulte os detalhes financeiros.</p></div><button onClick={()=>go("Financeiro")}>Ver cobranças →</button></section>}
    <section className="kpis"><Kpi icon="♙" label="Total de alunos" value={String(data.students.length)} note="↑ 8,4% nos últimos 30 dias" tone="blue"/><Kpi icon="↗" label="Receitas recebidas" value={money(revenue)} note="No mês atual" tone="green"/><Kpi icon="↘" label="Despesas" value={money(expense)} note="No mês atual" tone="orange"/><Kpi icon="!" label="Em atraso" value={money(overdue.reduce((a,t)=>a+t.amount,0))} note={`${overdue.length} cobrança pendente`} tone="red"/></section>
    <section className="dash-grid"><article className="card chart-card"><div className="card-head"><div><h2>Fluxo financeiro</h2><p>Receitas e despesas dos últimos meses</p></div><button onClick={()=>go("Relatórios")}>Ver relatório</button></div><div className="chart"><div className="axis"><span>12k</span><span>8k</span><span>4k</span><span>0</span></div>{[54,64,58,79,72,88].map((h,i)=><div className="month" key={i}><div><i style={{height:`${h}%`}}/><b style={{height:`${Math.max(20,h-30)}%`}}/></div><span>{["Mar","Abr","Mai","Jun","Jul","Ago"][i]}</span></div>)}</div><div className="legend"><span><i className="green"/>Receitas</span><span><i className="orange"/>Despesas</span></div></article>
      <article className="card overdue-list"><div className="card-head"><div><h2>Cobranças em atraso</h2><p>Ações rápidas por WhatsApp</p></div></div>{overdue.length?overdue.map(t=>{const s=data.students.find(x=>x.id===t.studentId)!;return <div className="charge" key={t.id}><span className="avatar">{s.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><strong>{s.name}</strong><small>Venceu em {new Date(t.dueDate+"T12:00:00").toLocaleDateString("pt-BR")}</small></div><b>{money(t.amount)}</b><button className="whatsapp" onClick={()=>whatsapp(s,t)}>◉ Cobrar</button></div>}):<div className="empty">Nenhuma mensalidade em atraso.</div>}</article></section>
    <section className="quick"><button onClick={()=>go("Financeiro")}><b>R$</b><span><strong>Abrir financeiro</strong><small>Pagamentos, despesas e cobranças</small></span>→</button><button onClick={()=>go("Documentos")}><b>▱</b><span><strong>Gerenciar documentos</strong><small>Anexos organizados por aluno</small></span>→</button><button onClick={()=>go("Relatórios")}><b>▤</b><span><strong>Consultar relatórios</strong><small>Indicadores para tomada de decisão</small></span>→</button></section>
  </>}
function Kpi({icon,label,value,note,tone}:{icon:string;label:string;value:string;note:string;tone:string}){return <article className={`kpi ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></article>}

function Students({data,onAdd,onOpen}:{data:Data;onAdd:()=>void;onOpen:(s:Student)=>void}){const [q,setQ]=useState("");const shown=data.students.filter(s=>`${s.name} ${s.classroom}`.toLowerCase().includes(q.toLowerCase()));return <><Heading title="Alunos" subtitle="Cadastros, contatos e informações financeiras."><button className="primary" onClick={onAdd}>＋ Novo aluno</button></Heading><div className="filters card"><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar por nome ou turma"/></label><span>{shown.length} alunos encontrados</span></div><div className="card table"><table><thead><tr><th>Aluno</th><th>Contato</th><th>Turma</th><th>Mensalidade</th><th>Vencimento</th><th></th></tr></thead><tbody>{shown.map(s=><tr key={s.id}><td><div className="student"><span>{s.name[0]}</span><div><strong>{s.name}</strong><small>Matrícula {new Date(s.enrollmentDate+"T12:00:00").toLocaleDateString("pt-BR")}</small></div></div></td><td>{s.phone}<small>{s.email}</small></td><td>{s.classroom}</td><td><strong>{money(s.monthlyFee)}</strong></td><td>Dia {s.dueDay}</td><td><button className="outline" onClick={()=>onOpen(s)}>Abrir ficha →</button></td></tr>)}</tbody></table></div></>}

function StudentProfile({student,data,close}:{student:Student;data:Data;close:()=>void}){const transactions=data.transactions.filter(t=>t.studentId===student.id);const documents=data.files.filter(f=>f.studentId===student.id);const overdue=transactions.find(t=>t.status==="atrasado");return <div className="modal-bg" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal profile-modal"><div className="modal-head profile-head"><div className="profile-title"><span>{student.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><div><h2>{student.name}</h2><p>Ficha completa do aluno • {student.classroom}</p></div></div><button onClick={close} aria-label="Fechar ficha">×</button></div><div className="profile-body"><section><h3>Dados pessoais e matrícula</h3><div className="profile-grid"><Info label="Nome completo" value={student.name}/><Info label="Turma" value={student.classroom}/><Info label="Data de matrícula" value={new Date(student.enrollmentDate+"T12:00:00").toLocaleDateString("pt-BR")}/><Info label="Código do aluno" value={`ALU-${String(student.id).padStart(4,"0")}`}/></div></section><section><h3>Responsável e contato</h3><div className="profile-grid"><Info label="E-mail" value={student.email}/><Info label="Telefone / WhatsApp" value={student.phone}/><Info label="Endereço" value={student.address} wide/></div></section><section><div className="profile-section-head"><h3>Informações financeiras</h3><span className={`status ${overdue?"atrasado":transactions.some(t=>t.status==="pendente")?"pendente":"pago"}`}>{overdue?"Em atraso":transactions.some(t=>t.status==="pendente")?"Pendente":"Em dia"}</span></div><div className="profile-grid"><Info label="Valor da mensalidade" value={money(student.monthlyFee)}/><Info label="Dia do vencimento" value={`Dia ${student.dueDay}`}/><Info label="Total de lançamentos" value={String(transactions.length)}/><Info label="Documentos anexados" value={String(documents.length)}/></div>{transactions.length>0&&<div className="mini-history">{transactions.map(t=><div key={t.id}><span><strong>{t.description}</strong><small>{t.dueDate?`Vencimento ${new Date(t.dueDate+"T12:00:00").toLocaleDateString("pt-BR")}`:"Movimentação financeira"}</small></span><b>{money(t.amount)}</b><em className={`status ${t.status}`}>{t.status==="pago"?"Pago":t.status==="atrasado"?"Em atraso":"Pendente"}</em></div>)}</div>}</section><section><h3>Documentos</h3>{documents.length?<div className="profile-docs">{documents.map(f=><a key={f.id} href={`/api/files?id=${f.id}`} target="_blank" rel="noreferrer">▱ <span><strong>{f.name}</strong><small>Visualizar documento</small></span>↗</a>)}</div>:<div className="profile-empty">Nenhum documento anexado à ficha deste aluno.</div>}</section></div><div className="profile-footer"><button className="outline" onClick={close}>Fechar</button>{overdue&&<button className="whatsapp" onClick={()=>whatsapp(student,overdue)}>◉ Enviar cobrança pelo WhatsApp</button>}</div></section></div>}
function Info({label,value,wide}:{label:string;value:string;wide?:boolean}){return <div className={wide?"info wide":"info"}><small>{label}</small><strong>{value}</strong></div>}

function Finance({data,reload,notify}:{data:Data;reload:()=>void;notify:(m:string)=>void}){const [status,setStatus]=useState("todos");const [q,setQ]=useState("");const shown=useMemo(()=>data.transactions.filter(t=>(status==="todos"||t.status===status)&&`${t.studentName||""} ${t.description}`.toLowerCase().includes(q.toLowerCase())),[data,status,q]);async function pay(id:number){await fetch("/api/crm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"pay",id})});await reload();notify("Pagamento confirmado e histórico atualizado.")}return <><Heading title="Financeiro" subtitle="Controle mensalidades, despesas, recebimentos e cobranças."><button className="primary">＋ Nova movimentação</button></Heading><section className="kpis small"><Kpi icon="✓" label="Recebido" value={money(data.transactions.filter(t=>t.type==="receita"&&t.status==="pago").reduce((a,t)=>a+t.amount,0))} note="Receitas confirmadas" tone="green"/><Kpi icon="◷" label="A receber" value={money(data.transactions.filter(t=>t.type==="receita"&&t.status==="pendente").reduce((a,t)=>a+t.amount,0))} note="Dentro do prazo" tone="blue"/><Kpi icon="!" label="Inadimplência" value={money(data.transactions.filter(t=>t.status==="atrasado").reduce((a,t)=>a+t.amount,0))} note="Ação necessária" tone="red"/></section><div className="filters card"><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar aluno ou movimentação"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos os status</option><option value="pago">Em dia / pago</option><option value="pendente">Pendente</option><option value="atrasado">Em atraso</option></select><input type="month" defaultValue="2026-08"/></div><div className="card table"><table><thead><tr><th>Aluno / movimentação</th><th>Vencimento</th><th>Valor</th><th>Tipo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{shown.map(t=>{const s=data.students.find(x=>x.id===t.studentId);return <tr key={t.id}><td><strong>{t.studentName||t.description}</strong><small>{t.studentName?t.description:"Movimentação administrativa"}</small></td><td>{t.dueDate?new Date(t.dueDate+"T12:00:00").toLocaleDateString("pt-BR"):"—"}</td><td><strong>{money(t.amount)}</strong></td><td><span className={`type ${t.type}`}>{t.type}</span></td><td><span className={`status ${t.status}`}>{t.status==="pago"?"Em dia":t.status==="atrasado"?"Em atraso":"Pendente"}</span></td><td><div className="actions">{t.status!=="pago"&&<button className="outline" onClick={()=>pay(t.id)}>Confirmar pagamento</button>}{t.status==="atrasado"&&s&&<button className="whatsapp" onClick={()=>whatsapp(s,t)}>◉ WhatsApp</button>}</div></td></tr>})}</tbody></table></div></>}

function Documents({data,reload,notify}:{data:Data;reload:()=>void;notify:(m:string)=>void}){const [studentId,setStudentId]=useState(data.students[0]?.id||0);async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const form=new FormData();form.set("file",file);form.set("studentId",String(studentId));const res=await fetch("/api/files",{method:"POST",body:form});if(res.ok){await reload();notify("Documento salvo na pasta do aluno.")}else notify((await res.json()).error||"Não foi possível enviar.")}return <><Heading title="Documentos" subtitle="Arquivos protegidos e organizados por aluno."/><div className="upload-card card"><div><span>↑</span><div><h2>Anexar novo arquivo</h2><p>PDF, imagem ou comprovante com até 10 MB.</p></div></div><select value={studentId} onChange={e=>setStudentId(Number(e.target.value))}>{data.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><label className="primary">Selecionar arquivo<input hidden type="file" onChange={upload}/></label></div><div className="document-grid">{data.students.map(s=>{const docs=data.files.filter(f=>f.studentId===s.id);return <article className="card folder" key={s.id}><span>▱</span><div><h3>{s.name}</h3><p>{s.classroom} • {docs.length} arquivo(s)</p></div>{docs.map(f=><a key={f.id} href={`/api/files?id=${f.id}`} target="_blank" rel="noreferrer"><b>{f.name}</b><small>Visualizar arquivo ↗</small></a>)}{!docs.length&&<small className="empty-doc">Nenhum documento anexado</small>}</article>})}</div></>}

function Reports({data}:{data:Data}){const rec=data.transactions.filter(t=>t.type==="receita"&&t.status==="pago").reduce((a,t)=>a+t.amount,0),des=data.transactions.filter(t=>t.type==="despesa").reduce((a,t)=>a+t.amount,0);return <><Heading title="Relatórios" subtitle="Indicadores claros para acompanhar a saúde financeira."/><section className="report-hero card"><div><small>RESULTADO DO PERÍODO</small><strong>{money(rec-des)}</strong><p>Saldo entre receitas confirmadas e despesas.</p></div><button className="primary" onClick={()=>window.print()}>↧ Imprimir relatório</button></section><div className="report-grid"><article className="card"><h2>Composição financeira</h2><div className="donut" style={{background:`conic-gradient(#23a88b 0 ${rec/(rec+des)*100}%, #ff9d5c 0)`}}><span>{Math.round(rec/(rec+des)*100)}%<small>receitas</small></span></div></article><article className="card"><h2>Resumo</h2><dl><div><dt>Receitas recebidas</dt><dd className="positive">{money(rec)}</dd></div><div><dt>Despesas registradas</dt><dd className="negative">{money(des)}</dd></div><div><dt>Alunos ativos</dt><dd>{data.students.length}</dd></div><div><dt>Mensalidades atrasadas</dt><dd>{data.transactions.filter(t=>t.status==="atrasado").length}</dd></div></dl></article></div></>}

function StudentForm({close,done}:{close:()=>void;done:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/crm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"student",...body})});if(res.ok)done();else setError((await res.json()).error)}return <div className="modal-bg"><section className="modal"><div className="modal-head"><div><h2>Cadastrar novo aluno</h2><p>Preencha os dados pessoais e financeiros.</p></div><button onClick={close}>×</button></div><form onSubmit={submit}><div className="form-grid"><label className="full">Nome completo<input name="name" required/></label><label>E-mail do responsável<input name="email" type="email" required/></label><label>Telefone / WhatsApp<input name="phone" required placeholder="(11) 99999-9999"/></label><label className="full">Endereço<input name="address" required/></label><label>Data de matrícula<input name="enrollmentDate" type="date" required/></label><label>Turma<input name="classroom" required placeholder="Ex.: 3º ano A"/></label><label>Mensalidade (R$)<input name="monthlyFee" type="number" min="0" step="0.01" required/></label><label>Dia do vencimento<input name="dueDay" type="number" min="1" max="28" required/></label></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="outline" onClick={close}>Cancelar</button><button className="primary">Salvar aluno</button></div></form></section></div>}
